// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqVEgcUaDzT_7ZpiO41M89RVVOFh0BrwU',
    appId: '1:214899307169:web:bacdcf71fd9de6e8f0b6e0',
    messagingSenderId: '214899307169',
    projectId: 'flutter-shop-app-bdff6',
    authDomain: 'flutter-shop-app-bdff6.firebaseapp.com',
    storageBucket: 'flutter-shop-app-bdff6.firebasestorage.app',
    measurementId: 'G-3TPRQTGE9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKLo2ruHsp7PbzNNizKoNDsVocOM42M9I',
    appId: '1:214899307169:android:cb68650df517a88bf0b6e0',
    messagingSenderId: '214899307169',
    projectId: 'flutter-shop-app-bdff6',
    storageBucket: 'flutter-shop-app-bdff6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-e9h6sglc5hy48-bdj7jfcbIXHy8OesU',
    appId: '1:214899307169:ios:db1ff648e87c53dff0b6e0',
    messagingSenderId: '214899307169',
    projectId: 'flutter-shop-app-bdff6',
    storageBucket: 'flutter-shop-app-bdff6.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-e9h6sglc5hy48-bdj7jfcbIXHy8OesU',
    appId: '1:214899307169:ios:db1ff648e87c53dff0b6e0',
    messagingSenderId: '214899307169',
    projectId: 'flutter-shop-app-bdff6',
    storageBucket: 'flutter-shop-app-bdff6.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqVEgcUaDzT_7ZpiO41M89RVVOFh0BrwU',
    appId: '1:214899307169:web:f10826620529df79f0b6e0',
    messagingSenderId: '214899307169',
    projectId: 'flutter-shop-app-bdff6',
    authDomain: 'flutter-shop-app-bdff6.firebaseapp.com',
    storageBucket: 'flutter-shop-app-bdff6.firebasestorage.app',
    measurementId: 'G-DTCW46WC34',
  );

}